### ISSUE TITLE
error when running truffle compile

### ISSUE THREAD

**Issue by gdiscord** [yam-finance/yamV3#5]
Facing the error below when running **truffle compile**.

How can it be resolved?

_... Compiling ./contracts/token/YAMTokenStorage.sol...
Error: spawnSync /bin/sh ENOBUFS
    at Object.spawnSync (internal/child_process.js:1041:20)
    at spawnSync (child_process.js:607:24)
    at execSync (child_process.js:652:15)
    at Object.compile (/usr/local/lib/node_modules/truffle/build/webpack:/packages/truffle-compile/compilerSupplier.js:310:1)
    at /usr/local/lib/node_modules/truffle/build/webpack:/packages/truffle-compile/index.js:130:1
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
Truffle v5.0.2 (core: 5.0.2)
Node v12.14.0_

**Comment by gnidan** [comment]
Hm, maybe try updating Truffle - 5.0.2 is pretty old. Latest is v5.1.46.

**Comment by brockelmore** [comment]
Closing. Let me know if updating didnt work
